[workspace]
resolver = "3"
members = ["graft", "aspen", "bmark"]
exclude = ["aspen-vid-converter"]

[profile.release]
lto = true

[profile.release-dbg]
inherits = "release"
lto = true
debug = true

[profile.dev]
opt-level = 1
